
# HARDCODED PARAMETERS
variable.transforms <- c("None", "Natural Log", "Cubic Root", "Categorical", "Binary")
smoothing.constructions <- c("te(x, y)", "s(x, y)", "s(x) + s(y)")

fluidPage(
  headerPanel("Interactive Visualization"),
  fluidRow(
    column(4,
           wellPanel(h4("Main"),
                     selectInput("X.COL", "X-Variable", ""),
                     selectInput("Y.COL", "Y-Variable / Categorical Variable", ""),
                     selectInput("Z.COL", "Z-Variable", "")),
           wellPanel(h4("Variable Transformations"),
                     selectInput("X.TRANSFORM", "X-Variable Transformation", variable.transforms),
                     selectInput("Y.TRANSFORM", "Y-Variable Transformation", variable.transforms),
                     selectInput("Z.TRANSFORM", "Z-Variable Transformation", variable.transforms)),
           wellPanel(h4("Data Filters"),
                     selectInput("STUDIES.SUBSET", "Selected Studies",
                                 "", selected="", multiple=TRUE),
                     selectInput("DIAGNOSIS.GROUP", "Diagnosis Group",
                                 "", selected="", multiple=TRUE),
                     selectInput("SEX.GROUP", "Sex Group",
                                 "", selected="", multiple=TRUE),
                     sliderInput("AGE.RANGE", "Age Range",
                                 min=0, max=100, value=c(0, 100), step=1)),
           wellPanel(h4("GAM Settings"),
                     sliderInput("GAM.K", "Number of Knots (Flexibility)",
                                 min=3, max=8, value=5, step=1),
                     sliderInput("GAM.GAMMA", "Gamma (Smoothness)",
                                 min=1, max=10, value=1, step=0.25),
                     selectInput("GAM.SMOOTHCONSTRUCTION",
                                 "Construction of Smoothing Term(s)",
                                 smoothing.constructions),
                     selectInput("GAM.COVARIATES", "Control for Biocovariates:",
                                 "", multiple=TRUE),
                     checkboxInput("GAM.STUDY", "Control for Study", FALSE))
           ),
    column(8,
           tabsetPanel(type="tabs",
                       tabPanel("Summary",
                                h4("Description of selected data:"),
                                tableOutput("summary_table"),
                                plotOutput("subject_counts_by_study")),
                       tabPanel("Histograms",
                                plotOutput("x_histogram"),
                                plotOutput("y_histogram"),
                                plotOutput("z_histogram")),
                       tabPanel("Scatterplots",
                                plotOutput("xy_scatter", height="600px"),
                                plotOutput("xz_scatter", height="600px"),
                                plotOutput("yz_scatter", height="600px")),
                       tabPanel("GAM",
                                h4("Summary of GAM fit:"),
                                verbatimTextOutput("gam_summary", placeholder=TRUE),
                                h4("Performance of GAM fit:"),
                                verbatimTextOutput("gam_performance", placeholder=TRUE),
                                h4("Output from gam.check():"),
                                verbatimTextOutput("gam_check", placeholder=TRUE)),
                       tabPanel("Persp",
                                plotOutput("gam_persp", height="600px"),
                                wellPanel(h4("Perspective Settings"),
                                          checkboxInput("PERSP.SE",
                                                        "Plot Standard Error Surfaces",
                                                        value=FALSE),
                                          checkboxInput("PERSP.POINTS",
                                                        "Plot Data Points",
                                                        value=FALSE),
                                          sliderInput("PERSP.THETA",
                                                      "Horizontal Rotation",
                                                      min=-360, max=0, value=-30, step=15),
                                          sliderInput("PERSP.PHI",
                                                      "Vertical Rotation",
                                                      min=0, max=360, value=15, step=15))
                                ),
                       tabPanel("Contours",
                                plotOutput("gam_contours", height="800px"),
                                wellPanel(h4("Contours Settings"),
                                          sliderInput("CONTOURS.SE",
                                                      "Show Confidence Bands: Number of SEs [Still Testing]",
                                                      min=0, max=5, value=0, step=0.05),
                                          checkboxInput("CONTOURS.POINTS",
                                                        "Plot Data Points",
                                                        value=TRUE),
                                          checkboxInput("CONTOURS.POINTCOLORS",
                                                        "Color Data Points (if plotted)",
                                                        value=TRUE),
                                          checkboxInput("CONTOURS.RSQ",
                                                        "Include R-Sqaure of Individual GAMs",
                                                        value=FALSE),
                                          sliderInput("CONTOURS.EXCLUSION",
                                                      "Grid Exclusion Distance",
                                                      min=0, max=0.5, value=0.1, step=0.01),
                                          sliderInput("CONTOURS.NLEVELS",
                                                      "Number of Contours",
                                                      min=1, max=30, value=10, step=1),
                                          sliderInput("CONTOURS.POINTSIZE",
                                                      "Point Size (if plotted)",
                                                      min=0, max=2, value=0.6, step=0.1))),
                       tabPanel("Partial",
                                plotOutput("gam_partial", height="600px"),
                                wellPanel(h4("Partial Dependency Settings"),
                                  sliderInput("PARTIAL.ALPHA",
                                              "CI Alpha (95% CI: alpha=0.05)",
                                              min=0, max=1, value=0.05, step=0.05))
                                ))
    )
  )
)



